nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-4.12.0.cjs


packageExtensions:
  "@openzeppelin/defender-sdk-base-client@*":
    # pnpm uses strict dependency rules
    # these are explicitly missing in the package.json of this package
    # but required by its code
    dependencies:
      axios: "^1.7.4"
      lodash: "^4.17.21"
