= Formula Correctness
:stem: asciimath

First of all, SKALE Network supposes that all points lie in the affine plane, not projective. In this case, all z-coordinates are equal to zero. Also, if we have point latexmath:[A(x_3,y_3,z_3)] in projective plane there is exactly one such point B on affine plane, that corresponds to A, and its coordinates latexmath:[B(x_3/z_3^2,y_3/z_3^3)].

Another important thing is that all coordinates are latexmath:[Fp_2] points and every coordinate has two other coordinates that are integers modulo 

latexmath:[p=21888242871839275222246405745257275088548364400416034343698204186575808495617]

Now, lets follow the algorithm provided by libff and see, that the result is the same.

latexmath:[H=x_2 - x_1]

latexmath:[I=4(x_2-x_1)^2]

latexmath:[J=H*I=4(x_2-x_1)^3]

latexmath:[r=2(s_2-s_1)=2(y_2-y_1)]

latexmath:[V=U_1*I=x_1*I=4x_1(x_2-x_1)^2]

latexmath:[X_3=r^2-J-2V=4(y_2-y_1)^2-4(x_2-x_1)^2-8x_1(x_2-x_1)^2]
latexmath:[Y_3=r*(V-X_3)-2S_1*J=r*(V-X_3)-2y_1*J=2(y_2-y_1)(4x_1(x_2-x_1)^2-X_3)-8y_1(x_2-x_1)^2]

latexmath:[Z_3=2H=2(x_2-x_1)]

latexmath:[x^*_3=x_3 / Z_3^2=(y_2-y_1/x_2-x_1)^2-(x_2-x_1)-2x_1=(y_2-y_1/x_2-x_1)^2-x_2-x_1]

latexmath:[y^*_3=Y_3/Z_3^3=8x_1(y_2-y_1)(x_2-x_1)^2/8(x_2-x_1)^3-2(y_2-y_1)x_3/Z_3^3-8y_1(x_2-x_1)^3/8(x_2-x_1)^3]

latexmath:[y^*_3=x_1(y_2-y_1)/(x_2-x_1)-x^*_3(y_2-y_1)/(x_2-x_1)-y_1]

Here we can see what we got from libff algorithm. Now, let’s follow algorithm from SKALE’s code.

latexmath:[s=(y_2-y_1)/(x_2-x_1)]

latexmath:[x_3=s^2-(x_1+x_2)=(y_2-y_1/x_2-x_1)^2-x_1-x_2]

latexmath:[y_3=-y_1-s*(x_3-x_1)=s*x_1-s*x_3-y_1=x_1(y_2-y_1/x_2-x_1)-x_3(y_2-y_1/x_2-x_1)-y_1]

As we can see, the result of both algorithms is the same.
