name: Nightly build
on:
  schedule:
    - cron:  '14 3 * * *'
env:
  NODE_VERSION: 24.x
  PYTHON_VERSION: 3.11

jobs:
  nightly-build-gas-without-node-rotation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install NODE JS
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: yarn

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: pip

    - name: Install project
      run: yarn install

    - name: Run gas measurements
      env:
        NODE_OPTIONS: --max_old_space_size=6952
      run: |
        rm gas/nodeRotation.ts
        yarn hardhat test gas/*.ts

  nightly-build-gas-node-rotation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install NODE JS
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: yarn

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: pip

    - name: Install project
      run: yarn install

    - name: Run gas measurements
      env:
        NODE_OPTIONS: --max_old_space_size=6952
      run: yarn hardhat test gas/nodeRotation.ts

  nightly-build-long-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install NODE JS
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: yarn

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: pip

    - name: Install project
      run: yarn install

    - name: Run long tests
      run: yarn hardhat test long-test/*
