name: Test

on:
  push:
    branches-ignore:
      - "docs-*"

env:
  NODE_VERSION: 24.x # In Active LTS until Oct 2026
  PYTHON_VERSION: 3.11

jobs:
  build-and-static-analysis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v6

      - name: Install NODE JS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install project
        run: yarn install

      - name: Compile contracts
        run: yarn cleanCompile

      - name: Install slither
        run: pip3 install -r scripts/requirements.txt

      - name: Show slither version
        run: slither --version

      - name: lint
        run: yarn fullCheck

      - name: Test ABI generation
        run: yarn hardhat run scripts/generateAbi.ts

      - name: Test types-package generation
        run: yarn buildTypes

  deployments-and-tests:
    runs-on: ubuntu-latest
    needs: build-and-static-analysis

    steps:
      - uses: actions/checkout@v6

      - name: Install NODE JS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install project
        run: yarn install

      - name: Compile contracts
        run: yarn cleanCompile

      - name: Test deployment
        run: ./scripts/test_deploy.sh

      - name: Test upgrade
        env:
          NODE_VERSION: ${{ env.NODE_VERSION }}
        run: ./scripts/test_upgrade.sh

      - name: Test transfer ownership
        run: TEST_MODE=true ./scripts/test_change_ownership.sh

      - name: Run tests
        env:
          NODE_OPTIONS: --max-old-space-size=12288
        run: yarn test

  coverage:
    name: Coverage (${{ matrix.shard.name }})
    runs-on: ubuntu-latest
    needs: build-and-static-analysis

    strategy:
      matrix:
        shard:
          - name: DKG
            files: "test/SkaleDKG.ts"
          - name: Schains
            files: "test/Schains.ts"
          - name: Others
            files: "test/**/!(SkaleDKG|Schains).ts"
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - name: Install NODE JS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install project
        run: yarn install

      - name: Compile contracts
        run: yarn cleanCompile

      - name: Run tests
        env:
          NODE_OPTIONS: --max-old-space-size=12288
        run: yarn hardhat coverage --solcoverjs .solcover.js --testfiles "${{ matrix.shard.files }}"

      - name: Prepare Coverage Report
        run: |
          mv coverage/coverage-final.json coverage-${{ matrix.shard.name }}.json

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true # Upload only the specified files
          files: coverage-${{ matrix.shard.name }}.json
          fail_ci_if_error: true
